FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /azp

RUN NET USER dockeruser "Password01!" /ADD

RUN NET LOCALGROUP "Administrators" "dockeruser" /ADD

COPY start.ps1 .

CMD powershell .\start.ps1